### ISSUE TITLE
i want to make the panel be blur 

### ISSUE THREAD

**Issue by jczhang02** [Mrcuve0/Aritim-Light#4]
can panel be blur ?
Like theme "sweet"?
How to do it?
Thanks!

**Comment by Mrcuve0** [comment]
Hi! 
The panel is already blurred as you can see from the image.

![Screenshot_20200326_100955](https://user-images.githubusercontent.com/36898760/77629524-f57b0f80-6f49-11ea-90dc-7f45823be259.png)

I reckon that it is hard to appreciate maybe due to the light nature of the theme, I guess I could try to add another version which is more transparent than the actual one. I will keep you informed, as it requires manipulating SVGs and I'm quite a noob with Inkscape right now 😅.

The main idea was to mimic the official "Breeze" theme, keeping the theme as "original as intended by KDE developers" as possible.

----

Just to be sure, as sometimes the "panel" word can be a little bit misleading, can you confirm me that you are not referring to the transparency of a common window, like in the following screenshot?

![Screenshot_20200326_100202](https://user-images.githubusercontent.com/36898760/77630061-c5803c00-6f4a-11ea-9192-f474ed95d2a1.png)

Because that would require an additional component called "kvantum" (hence defining a "kvantum-theme") that would require me some time to explore it since I never used it.

**Comment by jczhang02** [comment]
Hi!
To be honest, i didn't notice the blur effect. (Maybe the panel is white😂.
Thanks for your reply!
I Think it is a good theme. Wonderful! Haha!
And can i modify the blur effect by my self?
how to do it?
Thanks!
                                                                       Yours
                                                                        JCZhang
 发件人: Mrcuve0 <notifications@github.com>
发送时间: 2020年3月26日 17:18
收件人: Mrcuve0/Aritim-Light <Aritim-Light@noreply.github.com>
抄送: Flavius Buffon <jczhang@live.it>; Author <author@noreply.github.com>
主题: Re: [Mrcuve0/Aritim-Light] i want to make the panel be blur (#4)


Hi!
The panel is already blurred as you can see from the image.

[Screenshot_20200326_100955]<https://user-images.githubusercontent.com/36898760/77629524-f57b0f80-6f49-11ea-90dc-7f45823be259.png>

I reckon that it is hard to appreciate maybe due to the light nature of the theme, I guess I could try to add another version which is more transparent than the actual one. I will keep you informed, as it requires manipulating SVGs and I'm quite a noob with Inkscape right now 😅.

The main idea was to mimic the official "Breeze" theme, keeping the theme as "original as intended by KDE developers" as possible.

________________________________

Just to be sure, as sometimes the "panel" word can be a little bit misleading, can you confirm me that you are not referring to the transparency of a common window, like in the following screenshot?

[Screenshot_20200326_100202]<https://user-images.githubusercontent.com/36898760/77630061-c5803c00-6f4a-11ea-9192-f474ed95d2a1.png>

Because that would require an additional component called "kvantum" (hence defining a "kvantum-theme") that would require me some time to explore it since I never used it.

**Comment by Mrcuve0** [comment]
> I Think it is a good theme. Wonderful! Haha!

Thank you! I'm glad you like it! 😉

> And can i modify the blur effect by my self?
how to do it?

This is your documentation starting point, follow it carefully as it is very detailed --> https://techbase.kde.org/Development/Tutorials/Plasma5/Theme

The Plasma Theme is very likely located following this path: `/home/<your_username>/.local/share/plasma/desktoptheme/Aritim-Light/`.
Finally the SVG file to be modified is probably placed inside the `widgets` folder (probably it is the one called `background.svg`), you'll need to open it with Inkscape (or another tool able to handle SVG files).

I'd like to help you a little more than that but I too need to learn how to properly use Inkscape to modify certain files, but these days I'm quite busy with another project.

**Comment by jczhang02** [comment]
Ok I will learn it ！
Thanks！
And can I chat with you on some apps instead of mail?
Wechat is ok?(Maybe I will help the project)
Thanks


                                             Yours sincerely
                                             JC (from China)


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Mrcuve0** [comment]
You can find me on matrix: `@mrcuve0:matrix.org`, on Twitter `@Mrcuve0` or on email. 
I don't plan to move to other platforms, sorry.

**Comment by Mrcuve0** [comment]
Hi! I just wanted to let you know that I pushed a new version of the main Plasma Theme which has increased translucency (https://store.kde.org/p/1318993/). Just update the theme from System Settings if you want this new version.

I slightly modified the svg files following the documentation I posted before. Most of the modifications however can be done by directly modify the `metadata.desktop` file, especially the `[ContrastEffect]` fields at the end of the file (as specified in the aforementioned docs). 

Hope you like it, you can also modify it by changing these values that are pretty effective and customize it as you like. Cheers!
