### ISSUE TITLE
Kubuntu Dark text on Dark background in Settings 

### ISSUE THREAD

**Issue by VikramNisarga** [Mrcuve0/Aritim-Light#5]
When a selection is hovered, text and background  both will be dark making the text impossible to read

Steps to reproduce the behavior (if any):
For example:
1. Go to system settings > icons
2. Hover over icon back button

**Expected behavior**
Text should become light or the highlight color should be lighter

**Screenshots**
Before Hovering
![Before Hover](https://user-images.githubusercontent.com/26029452/80940782-6097eb80-8dfe-11ea-9901-a9d9a750adfb.png)

When Hovered
![hover](https://user-images.githubusercontent.com/26029452/80940808-6a215380-8dfe-11ea-90f1-475b46e8ffaa.png)

**Desktop (additional informations):**
 - OS: [Kubuntu 19.10]

 - KDE Plasma Version: 5.18.3
 - KDE Frameworks Version: 5.67.0

**Additional context**

**Comment by VikramNisarga** [comment]
In can see the same issue in Discover, Eclipse etc
In Discover and Thank you for your efforts
![image](https://user-images.githubusercontent.com/26029452/80941030-fcc1f280-8dfe-11ea-843a-8b5141bdbab1.png)

**Comment by Mrcuve0** [comment]
Thank you for reporting the issue!

This is the final result:
![Screenshot_20200504_184903](https://user-images.githubusercontent.com/36898760/80991213-f603a180-8e37-11ea-938a-c50ba438b9bc.png)

(Just a curiosity: the error is not on the text color, but on the hover background color, in fact. I observed that all the other themes don't change the text color neither)

I updated just now the `Aritim-Light` colorscheme. It may take sometime however to the opendesktop servers to update the packages, it may take let's say 15-30 minutes.

To update go to `System Settings` --> `Colors` --> `Get new Color Schemes` and look again for `Aritim-Light`, an update button should appear on the tile:

![Screenshot_20200504_185344](https://user-images.githubusercontent.com/36898760/80991651-a40f4b80-8e38-11ea-8836-aa387a08d9f0.png)

Let me know if there's anything other I can do 😁.

PS: If you have an account, you may want to leave a rating on my theme at the following page, it means a lot to me, thanks! --> https://www.pling.com/p/1290466/

**Comment by VikramNisarga** [comment]
Hello, I've verified, the issue is fixed. Thank you. 
If you're open to suggestions, Hover color is not consistent, if you too feel it is an issue, you can fix it when you have free time.
Ex:
**Hover on Menu items**
![HoverColor1](https://user-images.githubusercontent.com/26029452/81064510-6fae9480-8ef7-11ea-96bc-f5a65be7a524.png)
**Hover on Heading**
![HoverColor2](https://user-images.githubusercontent.com/26029452/81064542-7e954700-8ef7-11ea-998a-40fea289060c.png)

PS: I don't have an account right now but I'll create and leave a rating right  away.

**Comment by Mrcuve0** [comment]
Thank you once again for your rating!

I've fixed the hover colors, now they are all the same, much better ahah 😁

![Screenshot_20200505_162810](https://user-images.githubusercontent.com/36898760/81095542-73491800-8f05-11ea-8eb7-3a43252de934.png)

![Screenshot_20200505_192100](https://user-images.githubusercontent.com/36898760/81095635-996eb800-8f05-11ea-8018-f58b2099ffe6.png)

You can update again if you want

**Comment by VikramNisarga** [comment]
Hello @Mrcuve0 
Thanks again for your work. But looks like  the bug in Discover and Libre Office still exist. For example see below screenshots. I'm not sure if the issue is with the application or not(Close the ticket if it is).
Steps to reproduce
Open Discover and click on updates and select on any updatable item, there will momentary dark text on dark background

![Discover](https://user-images.githubusercontent.com/26029452/81264058-6be95200-905e-11ea-889a-7a150dae2168.png)

LibreOffice
![DarkOnDark](https://user-images.githubusercontent.com/26029452/81264478-18c3cf00-905f-11ea-8e9b-e33cd4422ed8.png)

**Comment by Mrcuve0** [comment]
Oh I see: last time I didn't check Discover since I need to install it (on Manjaro I solely use pacman from command line or octopi as a GUI, FYI).
Hence why I didn't notice this error, sometimes I tend to be a little bit approximative, my bad 😅.


DISCOVER
===

So I installed Discover and the problem seems to have source on the program rather than the theme itself. I'll tell you why:

So if you look down here at the screenshot, this is the result I get when I apply the "Arc"  colorsheme.

![Screenshot_20200507_122220](https://user-images.githubusercontent.com/36898760/81283762-6fc8a480-905d-11ea-9b4e-6d0fb0fe07ba.png)

As you can see, the problem is on the "selected item" color, not on the hover one (that should be now ok BTW). What we can see is that even with this colorscheme (that has been around for years now, so should be pretty complete and "glitch" free) the selected item is not so readable. Even worse, in my theme, the "blue" is quite stronger that Arc's one and hence the text becomes completely unreadable (or, in the other hand, the text does not swap to a "lighter" color in response).

Also, another hint that makes me think that Discover is currently "bugged" is that if I change colorscheme on the fly system-wide everything shifts to the new colorscheme but not Discover:

![Screenshot_20200507_123103](https://user-images.githubusercontent.com/36898760/81284634-a5ba5880-905e-11ea-9f24-e15dbb642c2d.png)

To apply the new colorscheme I actually have to close Discover and start it again: this should't be needed on a "classical" KDE/Qt application.

I'll investigate further more of course, but I think I'll probably end filling a bug form for the Discover team if there are none yet.

PS: Oh, BTW, I tried also w/ Breeze (which is the official theme) and the behavior is exactly the same.

I tried changing the "Selection Background" color to the same color used as "Hover Decoration" and you can see that, even if they are theoretically the same they are displayed differently (the hover one is lighter). 

So this may be a (maybe temporary) solution but, you know, I liked that accent color, it's hard to say goodbye to it 😂.

![Screenshot_20200507_124442](https://user-images.githubusercontent.com/36898760/81285926-8ae8e380-9060-11ea-914f-35a4594b3cb2.png)


LIBREOFFICE
===

This is probably due to the GTK2/3 theme that I have not checked yet. 
When dealing w/ GTK applications everything becomes quite tricky so I'll have to investigate quite more probably. As for now I'll concentrate my effort on Discover since it's, let's say, more inherent to Plasma itself.
